name: "Upload SARIF"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: /results.sarif
