name: "Upload SARIF"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  opensca-scan:
    name: "Run OpenSCA Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Execute OpenSCA Action
        uses: actions/action-test@v1
        with:
          token: ${{ secrets.OPENSCA_TOKEN }}
          out: outputs/results.json,outputs/results.html
          
